### ISSUE TITLE
Time Travel Queries Only Return Current Data State

### ISSUE THREAD

**Issue by aaj3f** [fluree/core#50]
## Description

> This is observed when running `server` on `feature/where-syntax-update` (commit SHA `7f125ccae182d4df5b1850ee64301291cf414954`)

Whether using ISO strings or commit integer values, time travel queries with the `t` keyword currently only return current data state.

The following two queries should throw an error for using an invalid time (e.g. no commit exists on the ledger in 1988 or at commit number 9999999999999)
```json
{
    "from": "cookbook/base",
    "select": {
        "ex:andrew": ["*"]
    },
    "t": "1988-05-30T12:40:44.823Z"
}
```
...
```json
{
    "from": "cookbook/base",
    "select": {
        "ex:andrew": ["*"]
    },
    "t": 9999999999999
}
```
Instead, both queries return data state as of latest commit.

Even a query with a valid `t` value (i.e. within the scope of the ledger's time/commit history) only returns data state as of latest commit

**Comment by mpoffald** [comment]
This was happening because the new federated queries (which is what this branch of`server` uses for all queries) were not passing along t values yet. I've got a fix in the works, but have questions:


1. If a query supplies multiple ledgers in a federated time-travel query, but that t is only valid for some of the ledgers, what should happen?  

Right now I have a branch where this is an error, and the query only returns data if the `t` is valid for _all_ the supplied ledgers. This was the most straightforward thing to implement, is this good enough for now?

2. About this query
```json
{
    "from": "cookbook/base",
    "select": {
        "ex:andrew": ["*"]
    },
    "t": 9999999999999
}
```

For datetime `t`s, we use the ["latest `t` value that is not more recent than that datetime"](https://github.com/fluree/db/blob/main/src/fluree/db/time_travel.cljc#L16). So if you use a datetime that is in the future relative to the db, you'll get data from the latest `t`.  It seems that this behavior for numeric `t` values is congruent with that -- if you don't yet have 9999999999999 commits, then you'll get results for your latest `t`. So I want to double-check that this needs to change.

**Comment by mpoffald** [comment]
Also want to note that what I'm implementing is the ability to supply a `t` that is used globally for all ledgers in the query. I found a [TODO](https://github.com/fluree/db/blob/main/src/fluree/db/api/query.cljc#L188) in our code that I believe refers to supporting individual `t`'s for each data source, but that would be a separate feature rather than part of this bugfix

**Comment by aaj3f** [comment]
This all makes sense @mpoffald -- the following are opinionated answers to your questions but I'm happy to discuss them more broadly in #fluree-core 

> If a federated time-travel query supplies multiple ledgers, but the t is only valid for some of the ledgers, what should happen?
> Right now I have a branch where this is an error, and the query only returns data if the t is valid for all the supplied ledgers. This was the most straightforward thing to implement, is this good enough for now?
> 

I think this is good enough for now, yes

> For datetime ts, we use the ["latest t value that is not more recent than that datetime"](https://github.com/fluree/db/blob/main/src/fluree/db/time_travel.cljc#L16). So if you use a datetime that is in the future relative to the db, you'll get data from the latest t. It seems that this behavior for numeric t values is congruent with that -- if you don't yet have 9999999999999 commits, then you'll get results for your latest t. So I want to double-check that this needs to change.

I think this is also fine and good
